--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.2

-- Started on 2024-12-15 15:30:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3587 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 24647)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO manager;

--
-- TOC entry 223 (class 1259 OID 24646)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: manager
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24590)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO manager;

--
-- TOC entry 226 (class 1259 OID 24660)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO manager;

--
-- TOC entry 225 (class 1259 OID 24659)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: manager
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24672)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO manager;

--
-- TOC entry 228 (class 1259 OID 24684)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO manager;

--
-- TOC entry 229 (class 1259 OID 24701)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO manager;

--
-- TOC entry 217 (class 1259 OID 24597)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "ApiKey" text,
    "Name" text,
    "Surname" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO manager;

--
-- TOC entry 238 (class 1259 OID 40974)
-- Name: CorrectDataPatterns; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."CorrectDataPatterns" (
    "Id" uuid NOT NULL,
    "Data" text NOT NULL,
    "CapturedTime" timestamp without time zone NOT NULL,
    "PhysicalDeviceId" uuid NOT NULL,
    "SensorId" uuid NOT NULL,
    "HasToleration" boolean DEFAULT false NOT NULL,
    "Toleration" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."CorrectDataPatterns" OWNER TO manager;

--
-- TOC entry 218 (class 1259 OID 24604)
-- Name: DeviceIcons; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."DeviceIcons" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Url" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."DeviceIcons" OWNER TO manager;

--
-- TOC entry 219 (class 1259 OID 24611)
-- Name: LoginProfiles; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."LoginProfiles" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "SshUsername" text,
    "SnmpSecurityName" text,
    "SnmpAuthenticationPassword" text,
    "SnmpPrivacyPassword" text,
    "SshPassword" text,
    "CiscoPrivilagedModePassword" text,
    "SnmpUsername" text
);


ALTER TABLE public."LoginProfiles" OWNER TO manager;

--
-- TOC entry 240 (class 1259 OID 73743)
-- Name: LoginProfilesToPhysicalDevices; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."LoginProfilesToPhysicalDevices" (
    "Id" uuid NOT NULL,
    "LoginProfileId" uuid NOT NULL,
    "PhysicalDeviceId" uuid NOT NULL
);


ALTER TABLE public."LoginProfilesToPhysicalDevices" OWNER TO manager;

--
-- TOC entry 230 (class 1259 OID 24725)
-- Name: PhysicalDevices; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."PhysicalDevices" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Platform" text NOT NULL,
    "MacAddress" text,
    "Capabilities" text,
    "IconId" uuid,
    "Version" text
);


ALTER TABLE public."PhysicalDevices" OWNER TO manager;

--
-- TOC entry 241 (class 1259 OID 73758)
-- Name: PhysicalDevicesHaveIpAddresses; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."PhysicalDevicesHaveIpAddresses" (
    "Id" uuid NOT NULL,
    "IpAddress" text NOT NULL,
    "PhysicalDeviceId" uuid NOT NULL
);


ALTER TABLE public."PhysicalDevicesHaveIpAddresses" OWNER TO manager;

--
-- TOC entry 231 (class 1259 OID 24742)
-- Name: PhysicalDevicesHavePorts; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."PhysicalDevicesHavePorts" (
    "Id" uuid NOT NULL,
    "PortId" uuid NOT NULL,
    "DeviceId" uuid NOT NULL
);


ALTER TABLE public."PhysicalDevicesHavePorts" OWNER TO manager;

--
-- TOC entry 220 (class 1259 OID 24625)
-- Name: Ports; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."Ports" (
    "Id" uuid NOT NULL,
    "Number" integer NOT NULL,
    "Protocol" integer NOT NULL,
    "IsDefault" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Ports" OWNER TO manager;

--
-- TOC entry 232 (class 1259 OID 24757)
-- Name: SchedulerJobs; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."SchedulerJobs" (
    "Id" uuid NOT NULL,
    "Cron" text NOT NULL,
    "Type" integer NOT NULL,
    "PhysicalDeviceId" uuid NOT NULL
);


ALTER TABLE public."SchedulerJobs" OWNER TO manager;

--
-- TOC entry 239 (class 1259 OID 49153)
-- Name: Settings; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."Settings" (
    "Id" uuid NOT NULL,
    "Key" text NOT NULL,
    "Value" text NOT NULL
);


ALTER TABLE public."Settings" OWNER TO manager;

--
-- TOC entry 237 (class 1259 OID 24828)
-- Name: SnmpSensorRecords; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."SnmpSensorRecords" (
    "Id" uuid NOT NULL,
    "Data" text NOT NULL,
    "CapturedTime" timestamp without time zone NOT NULL,
    "SensorId" uuid NOT NULL,
    "PhysicalDeviceId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);


ALTER TABLE public."SnmpSensorRecords" OWNER TO manager;

--
-- TOC entry 221 (class 1259 OID 24632)
-- Name: SnmpSensors; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."SnmpSensors" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Oid" text NOT NULL,
    "SnmpVersion" integer NOT NULL,
    "CommunityString" text NOT NULL,
    "IsMulti" boolean NOT NULL,
    "StartIndex" integer DEFAULT 0 NOT NULL,
    "EndIndex" integer DEFAULT 0 NOT NULL,
    "OidFilling" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."SnmpSensors" OWNER TO manager;

--
-- TOC entry 233 (class 1259 OID 24769)
-- Name: SnmpSensorsInPhysicalDevices; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."SnmpSensorsInPhysicalDevices" (
    "Id" uuid NOT NULL,
    "PhysicalDeviceId" uuid NOT NULL,
    "SnmpSensorId" uuid NOT NULL
);


ALTER TABLE public."SnmpSensorsInPhysicalDevices" OWNER TO manager;

--
-- TOC entry 234 (class 1259 OID 24784)
-- Name: SyslogRecords; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."SyslogRecords" (
    "Id" uuid NOT NULL,
    "Message" text NOT NULL,
    "CompletMessage" text NOT NULL,
    "PhysicalDeviceId" uuid,
    "Facility" integer DEFAULT 0 NOT NULL,
    "ProcessedDate" timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    "Severity" integer DEFAULT 0 NOT NULL,
    "Ip" text DEFAULT ''::text NOT NULL,
    "CreationDate" timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL
);


ALTER TABLE public."SyslogRecords" OWNER TO manager;

--
-- TOC entry 222 (class 1259 OID 24639)
-- Name: Tags; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."Tags" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Color" text NOT NULL
);


ALTER TABLE public."Tags" OWNER TO manager;

--
-- TOC entry 235 (class 1259 OID 24796)
-- Name: TagsOnPhysicalDevices; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."TagsOnPhysicalDevices" (
    "Id" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "TagId" uuid NOT NULL
);


ALTER TABLE public."TagsOnPhysicalDevices" OWNER TO manager;

--
-- TOC entry 236 (class 1259 OID 24811)
-- Name: Tickets; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."Tickets" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Text" text NOT NULL,
    "Created" bigint NOT NULL,
    "Updated" bigint NOT NULL,
    "DeviceId" uuid,
    "UserId" text NOT NULL
);


ALTER TABLE public."Tickets" OWNER TO manager;

--
-- TOC entry 215 (class 1259 OID 24585)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: manager
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO manager;

--
-- TOC entry 3564 (class 0 OID 24647)
-- Dependencies: 224
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3556 (class 0 OID 24590)
-- Dependencies: 216
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- TOC entry 3566 (class 0 OID 24660)
-- Dependencies: 226
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3567 (class 0 OID 24672)
-- Dependencies: 227
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- TOC entry 3568 (class 0 OID 24684)
-- Dependencies: 228
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- TOC entry 3569 (class 0 OID 24701)
-- Dependencies: 229
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- TOC entry 3557 (class 0 OID 24597)
-- Dependencies: 217
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."AspNetUsers" ("Id", "ApiKey", "Name", "Surname", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
23796a18-3d0c-4abe-9ee9-62ceee596a97	23796a18-3d0c-4abe-9ee9-62ceee596a97	Jarous	Nemec	jarous.nemec@gmail.com	JAROUS.NEMEC@GMAIL.COM	jarous.nemec@gmail.com	JAROUS.NEMEC@GMAIL.COM	t	AQAAAAIAAYagAAAAEGf6DAZ9QEnRWxy4misygIWhuas+C35Wn1ZKDjnQbkJvVqORZPTPCbTvmtxUVa5zrg==	2LXCEAETEMTPJA3NNU7VNSBEA5K6XNP3	d2958e20-6e96-417b-bbf4-5dd07cc3c284	\N	f	f	\N	t	0
e831f521-bdc8-420f-bc96-237301822be4	2a5ba24d-a613-4465-a1ea-372d8e5e9e43	\N	\N	franta	FRANTA	\N	\N	f	AQAAAAIAAYagAAAAEPfznjEpfrT9ocQdmiZmcypqs1iEvtAX5rE9QvF8W89GIC2pxT41YLqGmtNOtzqKsg==	YHN33NEJUQI7LOVTKDVDMDOIUZJSE6YG	9fe20491-5797-4bd8-abd5-eac9859efef6	\N	f	f	\N	t	0
\.


--
-- TOC entry 3578 (class 0 OID 40974)
-- Dependencies: 238
-- Data for Name: CorrectDataPatterns; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."CorrectDataPatterns" ("Id", "Data", "CapturedTime", "PhysicalDeviceId", "SensorId", "HasToleration", "Toleration") FROM stdin;
\.


--
-- TOC entry 3558 (class 0 OID 24604)
-- Dependencies: 218
-- Data for Name: DeviceIcons; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."DeviceIcons" ("Id", "Name", "Description", "Url") FROM stdin;
\.


--
-- TOC entry 3559 (class 0 OID 24611)
-- Dependencies: 219
-- Data for Name: LoginProfiles; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."LoginProfiles" ("Id", "Name", "Description", "SshUsername", "SnmpSecurityName", "SnmpAuthenticationPassword", "SnmpPrivacyPassword", "SshPassword", "CiscoPrivilagedModePassword", "SnmpUsername") FROM stdin;
\.


--
-- TOC entry 3580 (class 0 OID 73743)
-- Dependencies: 240
-- Data for Name: LoginProfilesToPhysicalDevices; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."LoginProfilesToPhysicalDevices" ("Id", "LoginProfileId", "PhysicalDeviceId") FROM stdin;
\.


--
-- TOC entry 3570 (class 0 OID 24725)
-- Dependencies: 230
-- Data for Name: PhysicalDevices; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."PhysicalDevices" ("Id", "Name", "Description", "Platform", "MacAddress", "Capabilities", "IconId", "Version") FROM stdin;
7c23bb8d-9daf-4a7a-9411-4f22ff6f131d	Switch 202	fdsafds	Cisco 2801	nevime	Router 	\N	cisco ios 15.8.0
\.


--
-- TOC entry 3581 (class 0 OID 73758)
-- Dependencies: 241
-- Data for Name: PhysicalDevicesHaveIpAddresses; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."PhysicalDevicesHaveIpAddresses" ("Id", "IpAddress", "PhysicalDeviceId") FROM stdin;
d4a5b407-9887-4e9d-955e-6122b3f3795f	10.1.1.20	7c23bb8d-9daf-4a7a-9411-4f22ff6f131d
116d839b-442e-417c-8094-3b3a4b64dd97	10.1.1.60	7c23bb8d-9daf-4a7a-9411-4f22ff6f131d
\.


--
-- TOC entry 3571 (class 0 OID 24742)
-- Dependencies: 231
-- Data for Name: PhysicalDevicesHavePorts; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."PhysicalDevicesHavePorts" ("Id", "PortId", "DeviceId") FROM stdin;
\.


--
-- TOC entry 3560 (class 0 OID 24625)
-- Dependencies: 220
-- Data for Name: Ports; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."Ports" ("Id", "Number", "Protocol", "IsDefault") FROM stdin;
0a6dd942-e46c-487b-8319-e852c32857e6	161	0	t
\.


--
-- TOC entry 3572 (class 0 OID 24757)
-- Dependencies: 232
-- Data for Name: SchedulerJobs; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."SchedulerJobs" ("Id", "Cron", "Type", "PhysicalDeviceId") FROM stdin;
\.


--
-- TOC entry 3579 (class 0 OID 49153)
-- Dependencies: 239
-- Data for Name: Settings; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."Settings" ("Id", "Key", "Value") FROM stdin;
ad098883-7136-4841-95cf-da6001b4f80f	DesiredSeverities	[0, 1, 2, 3, 4]
d99a2dd9-ac88-42f8-9f4c-8d72de3d69ee	ReportLogInterval	0 */2 * ? * *
3a40b332-7782-49e2-b7af-cc7c421c3542	ReportSensorInterval	0 */1 * ? * *
\.


--
-- TOC entry 3577 (class 0 OID 24828)
-- Dependencies: 237
-- Data for Name: SnmpSensorRecords; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."SnmpSensorRecords" ("Id", "Data", "CapturedTime", "SensorId", "PhysicalDeviceId") FROM stdin;
\.


--
-- TOC entry 3561 (class 0 OID 24632)
-- Dependencies: 221
-- Data for Name: SnmpSensors; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."SnmpSensors" ("Id", "Name", "Description", "Oid", "SnmpVersion", "CommunityString", "IsMulti", "StartIndex", "EndIndex", "OidFilling") FROM stdin;
e039aa6e-3e3f-4d22-98ec-1b87f50acdfa	Uptime	\N	.1.3.6.1.2.1.1.3.0	0	public	f	0	0	.
\.


--
-- TOC entry 3573 (class 0 OID 24769)
-- Dependencies: 233
-- Data for Name: SnmpSensorsInPhysicalDevices; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."SnmpSensorsInPhysicalDevices" ("Id", "PhysicalDeviceId", "SnmpSensorId") FROM stdin;
\.


--
-- TOC entry 3574 (class 0 OID 24784)
-- Dependencies: 234
-- Data for Name: SyslogRecords; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."SyslogRecords" ("Id", "Message", "CompletMessage", "PhysicalDeviceId", "Facility", "ProcessedDate", "Severity", "Ip", "CreationDate") FROM stdin;
\.


--
-- TOC entry 3562 (class 0 OID 24639)
-- Dependencies: 222
-- Data for Name: Tags; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."Tags" ("Id", "Name", "Description", "Color") FROM stdin;
\.


--
-- TOC entry 3575 (class 0 OID 24796)
-- Dependencies: 235
-- Data for Name: TagsOnPhysicalDevices; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."TagsOnPhysicalDevices" ("Id", "DeviceId", "TagId") FROM stdin;
\.


--
-- TOC entry 3576 (class 0 OID 24811)
-- Dependencies: 236
-- Data for Name: Tickets; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."Tickets" ("Id", "Name", "Text", "Created", "Updated", "DeviceId", "UserId") FROM stdin;
\.


--
-- TOC entry 3555 (class 0 OID 24585)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: manager
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240506221910_Initial	8.0.4
20240506222216_update	8.0.4
20240507213801_update snmp sensor and record model	8.0.4
20240508143905_changed structure of snmp record	8.0.4
20240508215127_added new table	8.0.4
20240510215301_update syslog	8.0.4
20240511160827_added settings	8.0.4
20240511212527_update syslog2	8.0.4
20240512212044_update correct pattern	8.0.4
20240518215558_update port	8.0.4
20240521215216_updated device	8.0.4
20240522144004_updated icon	8.0.4
20240523215210_deleted oid label	8.0.4
20240526190653_updated ph port relation	8.0.4
20240526191441_updated port2	8.0.4
20241109000057_UpdateSyslogRecord	8.0.4
20241214195317_RemoveDeviceAndUpdatedConcept	8.0.4
\.


--
-- TOC entry 3588 (class 0 OID 0)
-- Dependencies: 223
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: manager
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3589 (class 0 OID 0)
-- Dependencies: 225
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: manager
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3334 (class 2606 OID 24653)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3316 (class 2606 OID 24596)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3337 (class 2606 OID 24666)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3340 (class 2606 OID 65552)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3343 (class 2606 OID 24690)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3345 (class 2606 OID 65548)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3320 (class 2606 OID 24603)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3378 (class 2606 OID 40980)
-- Name: CorrectDataPatterns PK_CorrectDataPatterns; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."CorrectDataPatterns"
    ADD CONSTRAINT "PK_CorrectDataPatterns" PRIMARY KEY ("Id");


--
-- TOC entry 3323 (class 2606 OID 24610)
-- Name: DeviceIcons PK_DeviceIcons; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."DeviceIcons"
    ADD CONSTRAINT "PK_DeviceIcons" PRIMARY KEY ("Id");


--
-- TOC entry 3325 (class 2606 OID 24617)
-- Name: LoginProfiles PK_LoginProfiles; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."LoginProfiles"
    ADD CONSTRAINT "PK_LoginProfiles" PRIMARY KEY ("Id");


--
-- TOC entry 3384 (class 2606 OID 73747)
-- Name: LoginProfilesToPhysicalDevices PK_LoginProfilesToPhysicalDevices; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."LoginProfilesToPhysicalDevices"
    ADD CONSTRAINT "PK_LoginProfilesToPhysicalDevices" PRIMARY KEY ("Id");


--
-- TOC entry 3348 (class 2606 OID 24731)
-- Name: PhysicalDevices PK_PhysicalDevices; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."PhysicalDevices"
    ADD CONSTRAINT "PK_PhysicalDevices" PRIMARY KEY ("Id");


--
-- TOC entry 3387 (class 2606 OID 73764)
-- Name: PhysicalDevicesHaveIpAddresses PK_PhysicalDevicesHaveIpAddresses; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."PhysicalDevicesHaveIpAddresses"
    ADD CONSTRAINT "PK_PhysicalDevicesHaveIpAddresses" PRIMARY KEY ("Id");


--
-- TOC entry 3352 (class 2606 OID 73742)
-- Name: PhysicalDevicesHavePorts PK_PhysicalDevicesHavePorts; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."PhysicalDevicesHavePorts"
    ADD CONSTRAINT "PK_PhysicalDevicesHavePorts" PRIMARY KEY ("Id");


--
-- TOC entry 3327 (class 2606 OID 24631)
-- Name: Ports PK_Ports; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."Ports"
    ADD CONSTRAINT "PK_Ports" PRIMARY KEY ("Id");


--
-- TOC entry 3355 (class 2606 OID 24763)
-- Name: SchedulerJobs PK_SchedulerJobs; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SchedulerJobs"
    ADD CONSTRAINT "PK_SchedulerJobs" PRIMARY KEY ("Id");


--
-- TOC entry 3380 (class 2606 OID 49159)
-- Name: Settings PK_Settings; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."Settings"
    ADD CONSTRAINT "PK_Settings" PRIMARY KEY ("Id");


--
-- TOC entry 3374 (class 2606 OID 24834)
-- Name: SnmpSensorRecords PK_SnmpSensorRecords; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SnmpSensorRecords"
    ADD CONSTRAINT "PK_SnmpSensorRecords" PRIMARY KEY ("Id");


--
-- TOC entry 3329 (class 2606 OID 24638)
-- Name: SnmpSensors PK_SnmpSensors; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SnmpSensors"
    ADD CONSTRAINT "PK_SnmpSensors" PRIMARY KEY ("Id");


--
-- TOC entry 3359 (class 2606 OID 24773)
-- Name: SnmpSensorsInPhysicalDevices PK_SnmpSensorsInPhysicalDevices; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SnmpSensorsInPhysicalDevices"
    ADD CONSTRAINT "PK_SnmpSensorsInPhysicalDevices" PRIMARY KEY ("Id");


--
-- TOC entry 3362 (class 2606 OID 24790)
-- Name: SyslogRecords PK_SyslogRecords; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SyslogRecords"
    ADD CONSTRAINT "PK_SyslogRecords" PRIMARY KEY ("Id");


--
-- TOC entry 3331 (class 2606 OID 24645)
-- Name: Tags PK_Tags; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "PK_Tags" PRIMARY KEY ("Id");


--
-- TOC entry 3366 (class 2606 OID 24800)
-- Name: TagsOnPhysicalDevices PK_TagsOnPhysicalDevices; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."TagsOnPhysicalDevices"
    ADD CONSTRAINT "PK_TagsOnPhysicalDevices" PRIMARY KEY ("Id");


--
-- TOC entry 3370 (class 2606 OID 24817)
-- Name: Tickets PK_Tickets; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id");


--
-- TOC entry 3314 (class 2606 OID 24589)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3318 (class 1259 OID 24845)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3332 (class 1259 OID 24840)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3335 (class 1259 OID 24842)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3338 (class 1259 OID 24843)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3341 (class 1259 OID 24844)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3375 (class 1259 OID 40991)
-- Name: IX_CorrectDataPatterns_PhysicalDeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_CorrectDataPatterns_PhysicalDeviceId" ON public."CorrectDataPatterns" USING btree ("PhysicalDeviceId");


--
-- TOC entry 3376 (class 1259 OID 40992)
-- Name: IX_CorrectDataPatterns_SensorId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_CorrectDataPatterns_SensorId" ON public."CorrectDataPatterns" USING btree ("SensorId");


--
-- TOC entry 3381 (class 1259 OID 73771)
-- Name: IX_LoginProfilesToPhysicalDevices_LoginProfileId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_LoginProfilesToPhysicalDevices_LoginProfileId" ON public."LoginProfilesToPhysicalDevices" USING btree ("LoginProfileId");


--
-- TOC entry 3382 (class 1259 OID 73772)
-- Name: IX_LoginProfilesToPhysicalDevices_PhysicalDeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_LoginProfilesToPhysicalDevices_PhysicalDeviceId" ON public."LoginProfilesToPhysicalDevices" USING btree ("PhysicalDeviceId");


--
-- TOC entry 3385 (class 1259 OID 73773)
-- Name: IX_PhysicalDevicesHaveIpAddresses_PhysicalDeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_PhysicalDevicesHaveIpAddresses_PhysicalDeviceId" ON public."PhysicalDevicesHaveIpAddresses" USING btree ("PhysicalDeviceId");


--
-- TOC entry 3349 (class 1259 OID 24850)
-- Name: IX_PhysicalDevicesHavePorts_DeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_PhysicalDevicesHavePorts_DeviceId" ON public."PhysicalDevicesHavePorts" USING btree ("DeviceId");


--
-- TOC entry 3350 (class 1259 OID 24851)
-- Name: IX_PhysicalDevicesHavePorts_PortId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_PhysicalDevicesHavePorts_PortId" ON public."PhysicalDevicesHavePorts" USING btree ("PortId");


--
-- TOC entry 3346 (class 1259 OID 73770)
-- Name: IX_PhysicalDevices_IconId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_PhysicalDevices_IconId" ON public."PhysicalDevices" USING btree ("IconId");


--
-- TOC entry 3353 (class 1259 OID 24852)
-- Name: IX_SchedulerJobs_PhysicalDeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_SchedulerJobs_PhysicalDeviceId" ON public."SchedulerJobs" USING btree ("PhysicalDeviceId");


--
-- TOC entry 3371 (class 1259 OID 40962)
-- Name: IX_SnmpSensorRecords_PhysicalDeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_SnmpSensorRecords_PhysicalDeviceId" ON public."SnmpSensorRecords" USING btree ("PhysicalDeviceId");


--
-- TOC entry 3372 (class 1259 OID 24853)
-- Name: IX_SnmpSensorRecords_SensorId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_SnmpSensorRecords_SensorId" ON public."SnmpSensorRecords" USING btree ("SensorId");


--
-- TOC entry 3356 (class 1259 OID 24854)
-- Name: IX_SnmpSensorsInPhysicalDevices_PhysicalDeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_SnmpSensorsInPhysicalDevices_PhysicalDeviceId" ON public."SnmpSensorsInPhysicalDevices" USING btree ("PhysicalDeviceId");


--
-- TOC entry 3357 (class 1259 OID 24855)
-- Name: IX_SnmpSensorsInPhysicalDevices_SnmpSensorId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_SnmpSensorsInPhysicalDevices_SnmpSensorId" ON public."SnmpSensorsInPhysicalDevices" USING btree ("SnmpSensorId");


--
-- TOC entry 3360 (class 1259 OID 24856)
-- Name: IX_SyslogRecords_PhysicalDeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_SyslogRecords_PhysicalDeviceId" ON public."SyslogRecords" USING btree ("PhysicalDeviceId");


--
-- TOC entry 3363 (class 1259 OID 24857)
-- Name: IX_TagsOnPhysicalDevices_DeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_TagsOnPhysicalDevices_DeviceId" ON public."TagsOnPhysicalDevices" USING btree ("DeviceId");


--
-- TOC entry 3364 (class 1259 OID 24858)
-- Name: IX_TagsOnPhysicalDevices_TagId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_TagsOnPhysicalDevices_TagId" ON public."TagsOnPhysicalDevices" USING btree ("TagId");


--
-- TOC entry 3367 (class 1259 OID 24859)
-- Name: IX_Tickets_DeviceId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_Tickets_DeviceId" ON public."Tickets" USING btree ("DeviceId");


--
-- TOC entry 3368 (class 1259 OID 24860)
-- Name: IX_Tickets_UserId; Type: INDEX; Schema: public; Owner: manager
--

CREATE INDEX "IX_Tickets_UserId" ON public."Tickets" USING btree ("UserId");


--
-- TOC entry 3317 (class 1259 OID 24841)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: manager
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3321 (class 1259 OID 24846)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: manager
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3388 (class 2606 OID 24654)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3389 (class 2606 OID 24667)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3390 (class 2606 OID 24679)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3391 (class 2606 OID 24691)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3392 (class 2606 OID 24696)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3393 (class 2606 OID 24708)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3407 (class 2606 OID 40981)
-- Name: CorrectDataPatterns FK_CorrectDataPatterns_PhysicalDevices_PhysicalDeviceId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."CorrectDataPatterns"
    ADD CONSTRAINT "FK_CorrectDataPatterns_PhysicalDevices_PhysicalDeviceId" FOREIGN KEY ("PhysicalDeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3408 (class 2606 OID 40986)
-- Name: CorrectDataPatterns FK_CorrectDataPatterns_SnmpSensors_SensorId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."CorrectDataPatterns"
    ADD CONSTRAINT "FK_CorrectDataPatterns_SnmpSensors_SensorId" FOREIGN KEY ("SensorId") REFERENCES public."SnmpSensors"("Id") ON DELETE CASCADE;


--
-- TOC entry 3409 (class 2606 OID 73748)
-- Name: LoginProfilesToPhysicalDevices FK_LoginProfilesToPhysicalDevices_LoginProfiles_LoginProfileId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."LoginProfilesToPhysicalDevices"
    ADD CONSTRAINT "FK_LoginProfilesToPhysicalDevices_LoginProfiles_LoginProfileId" FOREIGN KEY ("LoginProfileId") REFERENCES public."LoginProfiles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3410 (class 2606 OID 73753)
-- Name: LoginProfilesToPhysicalDevices FK_LoginProfilesToPhysicalDevices_PhysicalDevices_PhysicalDevi~; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."LoginProfilesToPhysicalDevices"
    ADD CONSTRAINT "FK_LoginProfilesToPhysicalDevices_PhysicalDevices_PhysicalDevi~" FOREIGN KEY ("PhysicalDeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3411 (class 2606 OID 73765)
-- Name: PhysicalDevicesHaveIpAddresses FK_PhysicalDevicesHaveIpAddresses_PhysicalDevices_PhysicalDevi~; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."PhysicalDevicesHaveIpAddresses"
    ADD CONSTRAINT "FK_PhysicalDevicesHaveIpAddresses_PhysicalDevices_PhysicalDevi~" FOREIGN KEY ("PhysicalDeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3395 (class 2606 OID 73779)
-- Name: PhysicalDevicesHavePorts FK_PhysicalDevicesHavePorts_PhysicalDevices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."PhysicalDevicesHavePorts"
    ADD CONSTRAINT "FK_PhysicalDevicesHavePorts_PhysicalDevices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3396 (class 2606 OID 73784)
-- Name: PhysicalDevicesHavePorts FK_PhysicalDevicesHavePorts_Ports_PortId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."PhysicalDevicesHavePorts"
    ADD CONSTRAINT "FK_PhysicalDevicesHavePorts_Ports_PortId" FOREIGN KEY ("PortId") REFERENCES public."Ports"("Id") ON DELETE CASCADE;


--
-- TOC entry 3394 (class 2606 OID 73774)
-- Name: PhysicalDevices FK_PhysicalDevices_DeviceIcons_IconId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."PhysicalDevices"
    ADD CONSTRAINT "FK_PhysicalDevices_DeviceIcons_IconId" FOREIGN KEY ("IconId") REFERENCES public."DeviceIcons"("Id");


--
-- TOC entry 3397 (class 2606 OID 24764)
-- Name: SchedulerJobs FK_SchedulerJobs_PhysicalDevices_PhysicalDeviceId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SchedulerJobs"
    ADD CONSTRAINT "FK_SchedulerJobs_PhysicalDevices_PhysicalDeviceId" FOREIGN KEY ("PhysicalDeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3405 (class 2606 OID 40963)
-- Name: SnmpSensorRecords FK_SnmpSensorRecords_PhysicalDevices_PhysicalDeviceId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SnmpSensorRecords"
    ADD CONSTRAINT "FK_SnmpSensorRecords_PhysicalDevices_PhysicalDeviceId" FOREIGN KEY ("PhysicalDeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3406 (class 2606 OID 40968)
-- Name: SnmpSensorRecords FK_SnmpSensorRecords_SnmpSensors_SensorId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SnmpSensorRecords"
    ADD CONSTRAINT "FK_SnmpSensorRecords_SnmpSensors_SensorId" FOREIGN KEY ("SensorId") REFERENCES public."SnmpSensors"("Id") ON DELETE CASCADE;


--
-- TOC entry 3398 (class 2606 OID 24774)
-- Name: SnmpSensorsInPhysicalDevices FK_SnmpSensorsInPhysicalDevices_PhysicalDevices_PhysicalDevice~; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SnmpSensorsInPhysicalDevices"
    ADD CONSTRAINT "FK_SnmpSensorsInPhysicalDevices_PhysicalDevices_PhysicalDevice~" FOREIGN KEY ("PhysicalDeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3399 (class 2606 OID 24779)
-- Name: SnmpSensorsInPhysicalDevices FK_SnmpSensorsInPhysicalDevices_SnmpSensors_SnmpSensorId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SnmpSensorsInPhysicalDevices"
    ADD CONSTRAINT "FK_SnmpSensorsInPhysicalDevices_SnmpSensors_SnmpSensorId" FOREIGN KEY ("SnmpSensorId") REFERENCES public."SnmpSensors"("Id") ON DELETE CASCADE;


--
-- TOC entry 3400 (class 2606 OID 24791)
-- Name: SyslogRecords FK_SyslogRecords_PhysicalDevices_PhysicalDeviceId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."SyslogRecords"
    ADD CONSTRAINT "FK_SyslogRecords_PhysicalDevices_PhysicalDeviceId" FOREIGN KEY ("PhysicalDeviceId") REFERENCES public."PhysicalDevices"("Id");


--
-- TOC entry 3401 (class 2606 OID 24801)
-- Name: TagsOnPhysicalDevices FK_TagsOnPhysicalDevices_PhysicalDevices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."TagsOnPhysicalDevices"
    ADD CONSTRAINT "FK_TagsOnPhysicalDevices_PhysicalDevices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."PhysicalDevices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3402 (class 2606 OID 24806)
-- Name: TagsOnPhysicalDevices FK_TagsOnPhysicalDevices_Tags_TagId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."TagsOnPhysicalDevices"
    ADD CONSTRAINT "FK_TagsOnPhysicalDevices_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES public."Tags"("Id") ON DELETE CASCADE;


--
-- TOC entry 3403 (class 2606 OID 24818)
-- Name: Tickets FK_Tickets_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3404 (class 2606 OID 24823)
-- Name: Tickets FK_Tickets_PhysicalDevices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: manager
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_PhysicalDevices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."PhysicalDevices"("Id");


-- Completed on 2024-12-15 15:30:04

--
-- PostgreSQL database dump complete
--

